# Generated by Django 4.1.1 on 2022-09-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue_Resolver', '0002_category_type_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETED'), ('P', 'PENDING')], default='P', max_length=10),
        ),
    ]
