# Generated by Django 4.1.1 on 2022-09-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue_Resolver', '0003_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
