# Generated by Django 4.1.1 on 2022-09-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issue_Resolver', '0004_alter_issue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('room', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Issue_Resolver.type')),
            ],
        ),
    ]
